version: '2'
services:
  wallet_app:
    image: '636729331386.dkr.ecr.us-west-2.amazonaws.com/msa_wallet_app:latest'
    mem_limit: 200000000
    command: ./uwsgi.sh
    environment:
      AWS_REGION: us-west-2
      AWS_XRAY_DAEMON_ADDRESS: 'aws-xray-daemon:2000'
    links:
      - aws-xray-daemon
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: wallet_app
  wallet_nginx:
    image: '636729331386.dkr.ecr.us-west-2.amazonaws.com/msa_wallet_nginx:latest'
    mem_limit: 64000000
    links:
      - wallet_app
    ports:
      - '0:80'
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: wallet_nginx
  aws-xray-daemon:
    image: amazon/aws-xray-daemon
    mem_limit: 64000000
    ports:
      - '0:2000/udp'
    command:
      - /usr/bin/xray
      - '--bind'
      - '0.0.0.0:2000'
      - '--region'
      - us-west-2
      - '--buffer-memory'
      - '64'
      - '--log-level'
      - dev
      - '--log-file'
      - /dev/stdout
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: wallet_xray-daemon
