# Generated by Django 2.0.2 on 2019-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(default=0)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'balance_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'balance_transactiontype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('balance', models.IntegerField(default=3000)),
            ],
            options={
                'db_table': 'balance_wallet',
                'managed': False,
            },
        ),
    ]
